
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

homeassistant:
  name: Home
  unit_system: metric
  whitelist_external_dirs:
    - /tmp

  customize:
    sensor.ambient_temperature:
      icon: mdi:thermometer
      friendly_name: "Temperature"
    sensor.ambient_humidity:
      icon: mdi:weather-rainy
      friendly_name: "Humidity"
    sensor.ambient_pressure:
      icon: mdi:gauge
      friendly_name: "Pressure"
    camera.security_camera:
      friendly_name: "Security Camera"
    binary_sensor.motion_sensor:
      friendly_name: "Motion Sensor"
    switch.motion_led:
      friendly_name: "Motion LED"

#discovery:
#  ignore:
#    - homekit

#homekit:
#  auto_start: true
#  port: 51827
#  name: Home Assistant Bridge

ios:

stream:

camera:
  - platform: ffmpeg
    name: security_camera
    input: -rtsp_transport tcp -i rtsp://localhost:8554/unicast

notify:
  - name: family
    platform: group
    services:
      - service: ios_ceres
  
binary_sensor:
  - platform: rpi_gpio
    ports:
      23: motion_sensor 

switch:
  - platform: rpi_gpio
    ports: 
      24: motion_led
  - platform: broadlink
    #friendly_name: "Broadlink RM Mini 3"
    #type: rm_mini
    host: 192.168.0.50
    mac: "C8:F7:42:40:01:F8"
    #timeout: 15
    #retry: 5
    #switches:
    #  samsung_tv:
    #    friendly_name: "TV"
    #    command_on: ""
    #    command_off: ""

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    interval_seconds: 60
    consider_home: 180
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
