
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

homeassistant:
  name: Home
  unit_system: metric
  whitelist_external_dirs:
    - /tmp
  customize: !include customize.yaml

lovelace:
  mode: yaml

discovery:
#  ignore:
#    - homekit

homekit:
  name: Home Assistant
  filter:
    include_entities:
      - input_boolean.pieter_present
      - input_boolean.rouve_present

#ios:

stream:

camera:
  - platform: ffmpeg
    name: security_camera
    input: -rtsp_transport tcp -i rtsp://localhost:8554/unicast
    extra_arguments: "-vf hue=s=0"
  - platform: local_file
    name: security_camera_last_snapshot
    file_path: /home/homeassistant/.homeassistant/www/camera.security_camera_last.jpg
  # - platform: ffmpeg
  #   name: security_camera_last_clip
  #   input: "/home/homeassistant/.homeassistant/www/camera.security_camera_20191225-193224.mp4"

notify:
  - name: family
    platform: group
    services:
      - service: mobile_app_ceres
  
input_boolean:
  pieter_present:
    name: Pieter Presence
    icon: mdi:account
    #initial: ???
  rouve_present:
    name: Rouvé Presence
    icon: mdi:account

binary_sensor:
  - platform: rpi_gpio
    ports:
      23: motion_sensor 
  - platform: template
    sensors:
      pieter_present:
        friendly_name: "Pieter Present"
        value_template: >- 
          {{ is_state("input_boolean.pieter_present", "on") }}
      rouve_present:
        friendly_name: "Rouvé Present"
        value_template: >-
          {{ is_state("input_boolean.rouve_present", "on") }}
      anybody_home:
        friendly_name: "Anybody Home"
        value_template: >- 
          {{ is_state("binary_sensor.pieter_present", "on") or is_state("binary_sensor.rouve_present", "on") }} 
        #value_template: >-
        #  {{ is_state("person.pieter_rautenbach", "home") }}
        #device_class: presence # (On/Off)
        #value_template: >-
        #  {% set ns = namespace(found=false) %}
        #  {% for state in states.person %}
        #    {% if "state.state" == "home" %}
        #      {% set ns.found = true %}
        #    {% endif %}
        #  {% endfor %}
        #  {{ns.found}}

switch:
  - platform: rpi_gpio
    ports: 
      24: motion_led
  - platform: broadlink
    #friendly_name: "Broadlink RM Mini 3"
    #type: rm_mini
    host: !secret broadlink_host
    mac: "C8:F7:42:40:01:F8"
    #timeout: 15
    #retry: 5
    #switches:
    #  samsung_tv:
    #    friendly_name: "TV"
    #    command_on: ""
    #    command_off: ""

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    interval_seconds: 60 # scan interval
    #home_interval: 5 # minutes (scan interval)
    consider_home: 600 # seconds (timeout)
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

shell_command:
  noop: ":"
  copy_last_snapshot: "cp `ls -t /tmp/camera.security_camera_*.jpg | head -n1` /home/homeassistant/.homeassistant/www/camera.security_camera_last.jpg"
  # TODO: date +%s
  save_last_snapshot_date: "date > /home/homeassistant/.homeassistant/www/camera.security_camera_last.txt"

timer:
  motion_timer:
    duration: "00:05:00"