
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml

homeassistant:
  name: Home
  latitude: -33.9352105
  longitude: 18.8354788
  elevation: 130
  unit_system: metric
  time_zone: "Africa/Johannesburg"
  whitelist_external_dirs:
    - /tmp
  customize: !include customize.yaml

lovelace:
  mode: yaml

discovery:
#  ignore:
#    - homekit

homekit:
  name: Home Assistant
  filter:
    include_entities:
      - input_boolean.pieter_present
      - input_boolean.rouve_present
      - input_boolean.guest_mode
      - input_boolean.contractor_mode
      - light.smart_bulb_1

ios:
  push:
    categories:
      - name: Contractor Mode Still Enabled Alert
        identifier: "contractor_mode_still_enabled_alert"
        actions:
          - identifier: "DISABLE_CONTRACTOR_MODE"
            title: "Disable"
            # activationMode: "background"
            # authenticationRequired: true
            # behavior: "default"
      - name: Contractor Mode Enabled
        identifier: "contractor_mode_enabled"
        actions:
          - identifier: "DISABLE_CONTRACTOR_MODE"
            title: "Disable"
      - name: Contractor Mode Disabled
        identifier: "contractor_mode_disabled"
        actions:
          - identifier: "ENABLE_CONTRACTOR_MODE"
            title: "Enable"
      - name: Test
        identifier: 'test'
        actions:
          - identifier: 'TEST'
            title: 'Test Action'

zone:
  name: Home
  #hidden: true
  latitude: -33.9352105
  longitude: 18.8354788
  radius: 100
  friendly_name: Home
  icon: mdi:home

stream:

camera:
  - platform: ffmpeg
    name: security_camera
    input: -rtsp_transport tcp -i rtsp://localhost:8554/unicast
    extra_arguments: "-vf hue=s=0"
  - platform: local_file
    name: security_camera_last_snapshot
    file_path: /home/homeassistant/.homeassistant/www/camera.security_camera_last.jpg

notify:
  - name: family
    platform: group
    services:
      - service: mobile_app_ceres

input_boolean:
  pieter_present:
    name: Pieter Presence
    icon: mdi:account
    #initial: ???
  rouve_present:
    name: Rouvé Presence
    icon: mdi:account
  guest_mode:
    name: Guest Mode
    icon: mdi:briefcase
  contractor_mode:
    name: Contractor Mode
    icon: mdi:worker  

input_datetime:
  security_camera_last_snapshot:
    has_date: true
    has_time: true

binary_sensor:
  - platform: rpi_gpio
    ports:
      23: motion_sensor 
  - platform: template
    sensors:
      pieter_present:
        friendly_name: "Pieter Present"
        value_template: >- 
          {{ is_state("input_boolean.pieter_present", "on") }}
      rouve_present:
        friendly_name: "Rouvé Present"
        value_template: >-
          {{ is_state("input_boolean.rouve_present", "on") }}
      contractor_mode:
        friendly_name: "Contractor Mode"
        value_template: >-
          {{ is_state("input_boolean.contractor_mode", "on") }}
      anybody_home:
        friendly_name: "Anybody Home"
        value_template: >- 
          {{ is_state("input_boolean.pieter_present", "on") or is_state("input_boolean.rouve_present", "on") or 
             is_state("input_boolean.guest_mode", "on") or is_state("input_boolean.contractor_mode", "on") }} 

tplink:
  discovery: true
  # discovery: false
  # light:
  #   - host: 192.168.0.107

python_script:
# https://raw.githubusercontent.com/bieniu/ha-shellies-discovery/master/python_scripts/shellies_discovery.py

switch:
  - platform: rpi_gpio
    ports: 
      24: motion_led
  - platform: broadlink
    host: !secret broadlink_host
    mac: "C8:F7:42:40:01:F8"
  - platform: template
    switches:
      guest_mode:
        value_template: "{{ is_state('input_boolean.guest_mode', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.guest_mode
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.guest_mode
      contractor_mode:
        value_template: "{{ is_state('input_boolean.contractor_mode', 'on') }}"
        turn_on:
          - service: input_boolean.turn_on
            entity_id: input_boolean.contractor_mode
        turn_off:
          - service: input_boolean.turn_off
            entity_id: input_boolean.contractor_mode

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
    interval_seconds: 600 # scan interval
    #home_interval: 5 # minutes (scan interval)
    consider_home: 600 # seconds (timeout)
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false

shell_command:
  noop: ":"
  copy_last_snapshot_image: "cp `ls -t /tmp/camera.security_camera_*.jpg | head -n1` /home/homeassistant/.homeassistant/www/camera.security_camera_last.jpg"

timer:
  motion_timer:
    duration: "00:05:00"

input_number:
  wan_traffic_delta_in:
    min: 0
    max: 4294967295
  wan_traffic_delta_out:
    min: 0
    max: 4294967295

utility_meter:
  daily_internet_usage_in:
    source: sensor.internet_usage_in
    cycle: daily
  daily_internet_usage_out:
    source: sensor.internet_usage_out
    cycle: daily
  monthly_internet_usage_in:
    source: sensor.internet_usage_in
    cycle: monthly
  monthly_internet_usage_out:
    source: sensor.internet_usage_out
    cycle: monthly
