title: Home
background: var(--background-image)
views:
  - !include ui-lovelace/main.yaml
  - !include ui-lovelace/entertainment.yaml
  - !include ui-lovelace/internet.yaml
  - !include ui-lovelace/security.yaml
  - !include ui-lovelace/floorplan_new.yaml
  - !include ui-lovelace/floorplan_old.yaml
  - !include ui-lovelace/devices.yaml
  - !include ui-lovelace/test.yaml
