esphome:
  name: electricity_pulse_counter
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Electricity PC Fallback Hotspot"
    password: !secret fallback_ap_password

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret home_assistant_api_password

ota:
  password: !secret ota_password

# https://esphome.io/components/sensor/pulse_counter.html
sensor:
  - platform: pulse_counter
    pin: 34
    name: "Electricity Pulse Counter"
    unit_of_measurement: "kWh"
    update_interval: 60s

mqtt:
  broker: !secret mqtt_broker
  discovery: True
